apiVersion: v1
kind: Service
metadata:
  name: fe-react-nodeport-service
  labels:
    app: fe-react
    tier: frontend

spec:
  type: NodePort
  selector:
    app: fe-react
  ports:
    - name: http
      port: 80
      targetPort: 80
      # nodePort: 31234
