apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtail-web
  namespace: staging
  labels:
    app: mtail-web
    tier: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mtail-web
  template:
    metadata:
      labels:
        app: mtail-web
        tier: backend
    spec:
      initContainers:
        - name: init-db
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: mtail-web
          image: rghost/sharcst_mtail_web:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8095
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: mtail-web/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"

      imagePullSecrets:
        - name: regcred
      volumes:
        - name: postgres-initdb
          persistentVolumeClaim:
            claimName: postgres-pvc
